# Generated by Django 4.2.30 on 2026-04-20 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('qualidade', 'Problema de Qualidade'), ('quantidade', 'Quantidade Incorreta'), ('avaria', 'Produto Avariado'), ('prazo', 'Fora do Prazo'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('aprovada', 'Aprovada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=15)),
                ('destino_credito', models.CharField(choices=[('abatimento', 'Abatimento em Próxima Compra'), ('dinheiro', 'Devolução em Dinheiro / PIX'), ('estorno', 'Estorno no Cartão')], default='abatimento', max_length=15)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('nfe_devolucao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref. NF-e de Devolução')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Devolução de Venda',
                'verbose_name_plural': 'Devoluções de Venda',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('area_total_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Total (ha)')),
                ('coordenadas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Georreferenciamento')),
                ('car', models.CharField(blank=True, max_length=100, null=True, verbose_name='CAR (Cadastro Ambiental Rural)')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
            },
        ),
        migrations.CreateModel(
            name='Gleba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área (ha)')),
                ('coordenadas', models.CharField(blank=True, max_length=255, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glebas', to='gestao.fazenda')),
            ],
            options={
                'verbose_name': 'Gleba',
                'verbose_name_plural': 'Glebas',
            },
        ),
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de Cliente',
                'verbose_name_plural': 'Grupos de Clientes',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('balcao', 'Balcão'), ('produtor_rural', 'Produtor Rural'), ('cooperativa', 'Cooperativa'), ('orgao_publico', 'Órgão Público'), ('outros', 'Outros')], default='balcao', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fluxo_compra_completo',
            field=models.BooleanField(default=False, help_text='Habilita solicitação → cotação → aprovação → OC. Desativado = só recebimento de NF-e.', verbose_name='Fluxo de compra completo'),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='corredor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Corredor'),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='deposito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Depósito / Galpão'),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='nota_fiscal_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_gerados', to='gestao.notafiscal'),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='prateleira',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prateleira'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ean',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='EAN / Código de Barras'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ficha_tecnica',
            field=models.FileField(blank=True, null=True, upload_to='fichas_tecnicas/', verbose_name='Ficha Técnica'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fispq',
            field=models.FileField(blank=True, null=True, upload_to='fispq/', verbose_name='FISPQ'),
        ),
        migrations.AddField(
            model_name='produto',
            name='metodo_custeio',
            field=models.CharField(choices=[('cmp', 'Custo Médio Ponderado'), ('fifo', 'FIFO (Primeiro a Entrar, Primeiro a Sair)')], default='cmp', max_length=4, verbose_name='Método de Custeio'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(choices=[('insumo_agricola', 'Insumo Agrícola'), ('defensivo', 'Defensivo Agrícola'), ('semente', 'Semente'), ('fertilizante', 'Fertilizante'), ('produto_acabado', 'Produto Acabado'), ('colheita', 'Colheita'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilo'), ('LT', 'Litro'), ('MT', 'Metro'), ('PC', 'Peça'), ('CX', 'Caixa'), ('SC', 'Saca'), ('TON', 'Tonelada'), ('L', 'Litro (L)'), ('ML', 'Mililitro'), ('G', 'Grama')], default='UN', max_length=3, verbose_name='Unidade'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('veiculo', 'Veículo'), ('equipamento', 'Equipamento'), ('maquina', 'Máquina Agrícola')], default='veiculo', max_length=15)),
                ('descricao', models.CharField(max_length=255)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('crlv', models.FileField(blank=True, null=True, upload_to='crlv/', verbose_name='CRLV')),
                ('vencimento_doc', models.DateField(blank=True, null=True, verbose_name='Vencimento da Documentação')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='gestao.empresa')),
            ],
            options={
                'verbose_name': 'Veículo / Equipamento',
                'verbose_name_plural': 'Veículos / Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área (ha)')),
                ('cultura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cultura Plantada')),
                ('coordenadas', models.CharField(blank=True, max_length=255, null=True)),
                ('gleba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='gestao.gleba')),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
            },
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('canal_venda', models.CharField(choices=[('todos', 'Todos'), ('balcao', 'Balcão'), ('campo', 'Campo / Externo'), ('ecommerce', 'E-commerce')], default='todos', max_length=20)),
                ('regiao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabelas_preco', to='gestao.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_preco', to='gestao.empresa')),
                ('grupo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabelas_preco', to='gestao.grupocliente')),
            ],
            options={
                'verbose_name': 'Tabela de Preço',
                'verbose_name_plural': 'Tabelas de Preço',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino_estoque', models.CharField(choices=[('reposicao', 'Retorna ao Estoque'), ('descarte', 'Descarte')], default='reposicao', max_length=15)),
                ('justificativa_descarte', models.TextField(blank=True, null=True)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.devolucaovenda')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.loteestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.produto')),
            ],
            options={
                'verbose_name': 'Item de Devolução',
                'verbose_name_plural': 'Itens de Devolução',
            },
        ),
        migrations.AddField(
            model_name='grupocliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_cliente', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fazendas', to='gestao.cliente', verbose_name='Produtor / Proprietário'),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fazendas', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='devolucaovenda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='devolucaovenda',
            name='pedido_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='gestao.pedidovenda'),
        ),
        migrations.AddField(
            model_name='devolucaovenda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_abertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='gestao.grupocliente'),
        ),
        migrations.CreateModel(
            name='ItemTabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_tabela_preco', to='gestao.produto')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.tabelapreco')),
            ],
            options={
                'verbose_name': 'Item de Tabela de Preço',
                'verbose_name_plural': 'Itens de Tabela de Preço',
                'unique_together': {('tabela', 'produto')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grupocliente',
            unique_together={('empresa', 'nome')},
        ),
    ]
