# Generated by Django 4.2.30 on 2026-04-24 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_credito_cobranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoInadimplencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('indice_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_carteira', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_vencido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pdd_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_inadimplencia', to='gestao.empresa')),
            ],
            options={
                'verbose_name': 'Histórico de Inadimplência',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('empresa', 'mes', 'ano')},
            },
        ),
    ]
