# Generated by Django 4.2.30 on 2026-04-25 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_historico_inadimplencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosBarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('safra', models.CharField(blank=True, help_text='Ex: 2025/2026', max_length=20)),
                ('quantidade_sacas', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_referencia_manual', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fonte_preco_referencia', models.CharField(choices=[('manual', 'Cotação Manual'), ('cbot', 'CBOT (Integração)'), ('esalq', 'ESALQ (Integração)')], default='manual', max_length=10)),
                ('data_contrato', models.DateField()),
                ('data_entrega_prevista', models.DateField()),
                ('valor_insumos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('entregue', 'Entregue'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_barter', to='gestao.empresa')),
                ('produto_receber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barters_receber', to='gestao.produto')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_barter', to='gestao.cliente')),
            ],
            options={
                'verbose_name': 'Contrato Barter',
                'ordering': ['-data_entrega_prevista'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ContratoTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('compra', 'Compra Futura'), ('venda', 'Venda Futura')], max_length=10)),
                ('contraparte_nome', models.CharField(blank=True, max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_travado', models.DecimalField(decimal_places=4, max_digits=12)),
                ('data_contrato', models.DateField()),
                ('data_entrega', models.DateField()),
                ('safra', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('preco_mercado_manual', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fonte_preco_mercado', models.CharField(choices=[('manual', 'Cotação Manual'), ('cbot', 'CBOT (Integração)'), ('esalq', 'ESALQ (Integração)')], default='manual', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contraparte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_termo', to='gestao.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_termo', to='gestao.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_termo', to='gestao.produto')),
            ],
            options={
                'verbose_name': 'Contrato a Termo',
                'ordering': ['data_entrega'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='CPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('quantidade_sacas', models.DecimalField(decimal_places=3, max_digits=12)),
                ('qualidade_minima', models.TextField(blank=True)),
                ('local_entrega', models.CharField(blank=True, max_length=255)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_credito', models.DecimalField(decimal_places=2, max_digits=15)),
                ('garantias', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('liquidada_fisica', 'Liquidada Fisicamente'), ('liquidada_financeira', 'Liquidada Financeiramente'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('preco_mercado_manual', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fonte_preco', models.CharField(choices=[('manual', 'Cotação Manual'), ('cbot', 'CBOT (Integração)'), ('esalq', 'ESALQ (Integração)')], default='manual', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cprs_emitidas', to='gestao.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cprs', to='gestao.empresa')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cprs', to='gestao.pedidovenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cprs', to='gestao.produto')),
            ],
            options={
                'verbose_name': 'CPR',
                'ordering': ['-data_vencimento'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ItemBarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.contratosbarter')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.pedidovenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_barter', to='gestao.produto')),
            ],
            options={
                'verbose_name': 'Item de Barter',
            },
        ),
        migrations.CreateModel(
            name='EntregaTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('quantidade_entregue', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_entrega', models.DecimalField(decimal_places=4, max_digits=12)),
                ('resultado_financeiro', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nota_fiscal', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='gestao.contratotermo')),
            ],
            options={
                'verbose_name': 'Entrega a Termo',
                'ordering': ['data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='EntregaCPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('quantidade_entregue', models.DecimalField(decimal_places=3, max_digits=12)),
                ('nota_fiscal_entrada', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='gestao.cpr')),
            ],
            options={
                'verbose_name': 'Entrega de CPR',
                'ordering': ['data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='EntregaBarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('quantidade_entregue', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_entrega_manual', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fonte_preco_entrega', models.CharField(choices=[('manual', 'Cotação Manual'), ('cbot', 'CBOT (Integração)'), ('esalq', 'ESALQ (Integração)')], default='manual', max_length=10)),
                ('ajuste_financeiro', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nota_fiscal_entrada', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='gestao.contratosbarter')),
            ],
            options={
                'verbose_name': 'Entrega de Barter',
                'ordering': ['data_entrega'],
            },
        ),
    ]
