# Generated by Django 4.2.30 on 2026-04-28 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_superhost_2fa_planos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vendedor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteira_clientes', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Responsável'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('inadimplente', 'Inadimplente'), ('atrasado', 'Inadimplente')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('alteracao_preco', 'Alteração de Preço'), ('alteracao_estoque', 'Alteração de Estoque'), ('alteracao_permissao', 'Alteração de Permissão'), ('exclusao', 'Exclusão de Registro'), ('aprovacao_pedido', 'Aprovação de Pedido'), ('recusa_pedido', 'Recusa de Pedido'), ('expiracao_automatica', 'Expiração Automática de Pedido'), ('expiracao_manual', 'Expiração Manual de Pedido'), ('faturamento', 'Faturamento de Pedido'), ('login', 'Login no Sistema'), ('alteracao_usuario', 'Alteração de Usuário'), ('manifestacao_nfe', 'Manifestação de NF-e'), ('cancelamento_nfe', 'Cancelamento de NF-e'), ('carta_correcao_nfe', 'Carta de Correção NF-e'), ('venda_pdv', 'Venda PDV'), ('cancelamento_pdv', 'Cancelamento de Venda PDV'), ('acesso_superhost', 'Acesso SuperHost ao Ambiente'), ('bloqueio_empresa', 'Bloqueio/Desbloqueio de Empresa'), ('alteracao_tipo_empresa', 'Alteração de Tipo de Empresa'), ('transferencia_carteira', 'Transferência de Carteira')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('validade_lote', 'Lote Próximo do Vencimento'), ('conta_vencer', 'Conta a Pagar Vencendo'), ('boleto_vencer', 'Boleto do Cliente Vencendo'), ('cliente_inadimplente', 'Cliente Inadimplente'), ('cliente_sem_comprar', 'Cliente Sem Comprar'), ('aniversario', 'Aniversário do Cliente'), ('pedido_retido', 'Pedido Retido para Aprovação'), ('pedido_aprovado', 'Pedido Aprovado — aguardando conclusão do vendedor'), ('pedido_expirado', 'Pedido Expirado por Prazo'), ('meta_atingida', 'Meta Atingida'), ('pos_venda', 'Pós-venda — Contato após faturamento'), ('data_comemorativa', 'Data Comemorativa'), ('contingencia_sefaz', 'Contingência SEFAZ Ativa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('diretor', 'Nível 1 - Diretor'), ('gerente', 'Nível 2 - Gerente'), ('vendedor', 'Nível 3 - Vendedor'), ('administrativo', 'Nível 4 - Administrativo / Financeiro'), ('operacional', 'Nível 5 - Operacional / Balcão'), ('rh', 'Nível 6 - RH')], default='vendedor', max_length=20),
        ),
    ]
