# Generated by Django 4.2.30 on 2026-04-28 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_carteira_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('telefone', 'Ligação Telefônica'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('video', 'Videoconferência')], default='presencial', max_length=15)),
                ('data_visita', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, default='')),
                ('resultado', models.CharField(choices=[('positivo', 'Positivo'), ('neutro', 'Neutro'), ('negativo', 'Negativo'), ('sem_contato', 'Sem Contato')], default='neutro', max_length=15)),
                ('proximo_contato', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='gestao.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_clientes', to='gestao.empresa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita a Cliente',
                'verbose_name_plural': 'Visitas a Clientes',
                'ordering': ['-data_visita'],
            },
        ),
    ]
