# Generated by Django 4.2.30 on 2026-04-28 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_aplicacao_insumo_plano_contas_producao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contacontabil',
            name='unique_conta_por_empresa',
        ),
        migrations.RemoveConstraint(
            model_name='ordemproducao',
            name='unique_op_por_empresa',
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Null = conta padrão do sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_contabeis', to='gestao.empresa'),
        ),
        migrations.AlterField(
            model_name='grupocontabil',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Null = grupo padrão do sistema compartilhado por todas as empresas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_contabeis', to='gestao.empresa'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('alteracao_preco', 'Alteração de Preço'), ('alteracao_estoque', 'Alteração de Estoque'), ('alteracao_permissao', 'Alteração de Permissão'), ('exclusao', 'Exclusão de Registro'), ('aprovacao_pedido', 'Aprovação de Pedido'), ('recusa_pedido', 'Recusa de Pedido'), ('expiracao_automatica', 'Expiração Automática de Pedido'), ('expiracao_manual', 'Expiração Manual de Pedido'), ('faturamento', 'Faturamento de Pedido'), ('login', 'Login no Sistema'), ('alteracao_usuario', 'Alteração de Usuário'), ('manifestacao_nfe', 'Manifestação de NF-e'), ('cancelamento_nfe', 'Cancelamento de NF-e'), ('carta_correcao_nfe', 'Carta de Correção NF-e'), ('venda_pdv', 'Venda PDV'), ('cancelamento_pdv', 'Cancelamento de Venda PDV'), ('acesso_superhost', 'Acesso SuperHost ao Ambiente'), ('bloqueio_empresa', 'Bloqueio/Desbloqueio de Empresa'), ('alteracao_tipo_empresa', 'Alteração de Tipo de Empresa'), ('transferencia_carteira', 'Transferência de Carteira'), ('criacao', 'Criação de Registro'), ('edicao', 'Edição de Registro')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='contacontabil',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='ordemproducao',
            unique_together={('empresa', 'numero')},
        ),
    ]
