# Generated by Django 4.2.30 on 2026-04-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_remove_contacontabil_unique_conta_por_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('historico', models.CharField(max_length=255, verbose_name='Histórico')),
                ('origem_tipo', models.CharField(blank=True, choices=[('conta_pagar', 'Conta a Pagar'), ('conta_receber', 'Conta a Receber'), ('venda_pdv', 'Venda PDV'), ('manual', 'Lançamento Manual')], max_length=20)),
                ('origem_id', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_credito', to='gestao.contacontabil')),
                ('conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_debito', to='gestao.contacontabil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_contabeis', to='gestao.empresa')),
            ],
            options={
                'verbose_name': 'Lançamento Contábil',
                'verbose_name_plural': 'Lançamentos Contábeis',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MapaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('conta_pagar_paga', 'Pagamento de Conta a Pagar'), ('conta_receber_recebida', 'Recebimento de Conta a Receber'), ('venda_pdv', 'Venda PDV'), ('compra_estoque', 'Entrada de Estoque por Compra'), ('sangria_caixa', 'Sangria de Caixa'), ('suprimento_caixa', 'Suprimento de Caixa')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapa_credito', to='gestao.contacontabil', verbose_name='Conta de Crédito')),
                ('conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapa_debito', to='gestao.contacontabil', verbose_name='Conta de Débito')),
                ('empresa', models.ForeignKey(blank=True, help_text='Null = mapeamento padrão do sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapa_contabil', to='gestao.empresa')),
            ],
            options={
                'verbose_name': 'Mapa Contábil',
                'verbose_name_plural': 'Mapa Contábil',
                'unique_together': {('empresa', 'tipo_operacao')},
            },
        ),
    ]
