# Generated by Django 4.2.30 on 2026-04-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_mapa_lancamento_contabil'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissaogranular',
            name='empresas_adicionais',
            field=models.ManyToManyField(blank=True, help_text='Empresas do grupo às quais este usuário tem acesso além da própria.', related_name='gerentes_com_acesso', to='gestao.empresa', verbose_name='Empresas adicionais com acesso'),
        ),
    ]
