# Generated by Django 4.2.30 on 2026-05-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_permissao_empresas_adicionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('caminhao', 'Caminhão'), ('van', 'Van / VUC'), ('pickup', 'Pickup'), ('trator', 'Trator'), ('outro', 'Outro')], default='veiculo', max_length=15),
        ),
    ]
